### ISSUE TITLE
Output socket's color for ALL ?

### ISSUE THREAD

**Issue by Apollon-Theos** [dizzyd/Mekanism#10]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Wind Generator have GREEN socket, but this socket only for output.
Maybe I am mistaken?

![mekanism-005](https://user-images.githubusercontent.com/46534073/53665128-98942380-3c7b-11e9-901e-6b7c9d727732.jpg)

#### Steps to reproduce:
1. by desing
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:**  2805
**Mekanism:** 9.4.17
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by dizzyd** [comment]
Hi @Apollon-Theos - changing this would be quite significant and I'm not sure I'm ready to take on something of this scope. If you want to start by submitting a patch for the wind generators, we can discuss scaling that out to all the other models. :)
