### ISSUE TITLE
Base blocks and their upgrades

### ISSUE THREAD

**Issue by TheSnowyChickens** [dizzyd/Mekanism#12]
#### Issue description:
The factory blocks are not disabled, if the base block is disabled.
Example -> I disabled the combiner, but the factories from the combiner are not disabled and still visible in JEI and in the creative tab. (+ the recipes are still there)

Edit: in JEI the recipes are also visible.

#### Steps to reproduce:
1. go in your config and disable the combiner
2. start the game
3. look at the factories of the combiner

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2815
**Mekanism:** Dz-1.12.2-9.4.17
**Other relevant version:** JEI 264

**Comment by dizzyd** [comment]
This will be fixed in the next release, 9.4.18. I expect I'll release tomorrow sometime.
