### ISSUE TITLE
Some textures are larger than they need to be

### ISSUE THREAD

**Issue by GreatestFool** [dizzyd/Mekanism#14]
Apologies if this is not an issue in this fork. I created this issue yesterday or so on the main branch, didn't even notice Mekanism hasn't been updated in so long, thanks for maintaining this fork.

> Some [textures are way to large](http://i.imgur.com/KhSch6I.png) ([alternate version with gray background](http://i.imgur.com/jthUSY0.png)), 128x128 without using even half of that size. With only vanilla it covers ~88% of the texture atlas, even with over 150 mods it covers ~35%. That in and of itself would not be an issue had it not been for the fact that some textures, generators or blocks with multiple faces are the normal contender, but I can't remember the names of every block.

> Cables are 48x48, and while much to big for my liking are fine because they don't waste space in the texture atlas.

> I'm pretty sure you should be able to cut down the sizes of the generators or blocks by a bit, though I don't know if there is some strange reason for them being this way. I still thought I should make an issue report on it.

**Comment by dizzyd** [comment]
I'm happy to look into this, but would love to understand more about how you're measuring this. Any tools/techniques you can point me at?

**Comment by jburrows82** [comment]
The tool he's referencing the texture atlas percentage by mod is called [TextureDump](https://www.reddit.com/r/feedthebeast/comments/5b6bwg/exploring_the_texture_map/) by mezz. A couple years ago mezz posted about the vanilla atlas texture bug and subsequently mods bloating the texture atlas with larger than needed textures such as these in Mekanism.

mezz did post any issue https://github.com/aidancbrady/Mekanism/issues/3920 to bring awareness, in which @CyanideX supposedly was going to clean up the textures to resolve the bloat. I'm guessing that never happened, or the changes never made it in the project.

**Comment by CyanideX** [comment]
They did get done but I'm not sure what happened to them. I haven't been involved with Minecraft for quite some time. 😔

**Comment by dizzyd** [comment]
@CyanideX - I don't suppose you still have the adjusted source material? I know it's been a while, so no worries if not. Otherwise, I guess I'll have to learn how to adjust textures (lol). :)

**Comment by CyanideX** [comment]
I'm sure I have it somewhere. I'm a little swamped with work at the moment but I will try to take a look for them as soon as I have some free time.

RemindMe! 364 days

**Comment by dizzyd** [comment]
@GreatestFool @jburrows82 @CyanideX - please note this issue has been moved to here: https://github.com/mekanica/mekanica/issues/2
