### ISSUE TITLE
Expanded Integration Support

### ISSUE THREAD

**Issue by bookerthegeek** [dizzyd/Mekanism#16]
# Heyo!
First, thank you so very much for doing this. I hope this fork goes well for you. :) Now, onto my request.

So in the CraftTweaker/ModTweaker integration, lets say the crusher, for example (although this is an issue for all of the machines), I want to add a recipe that will turn one copper ore into three copper dust (instead of two). Now to do that the following script is used first to remove the old recipes and then add the new ones. I'm actually using TechReborn for ore unification reasons and am switching all outputs to that mods items.
```
// Remove Copper
	enrichment.removeRecipe(<embers:ore_copper>);	
	enrichment.removeRecipe(<forestry:resources:1>);	
	enrichment.removeRecipe(<immersiveengineering:ore>);	
	enrichment.removeRecipe(<mekanism:oreblock:1>);	
	enrichment.removeRecipe(<projectred-exploration:ore:3>);	
	enrichment.removeRecipe(<railcraft:ore_metal>);	
	enrichment.removeRecipe(<techreborn:ore2>);	
	enrichment.removeRecipe(<thermalfoundation:ore>);	
// Add Copper
	enrichment.addRecipe(<embers:ore_copper>, <techreborn:dust:14> * 3);
	enrichment.addRecipe(<forestry:resources:1>, <techreborn:dust:14> * 3);
	enrichment.addRecipe(<immersiveengineering:ore>, <techreborn:dust:14> * 3);
	enrichment.addRecipe(<mekanism:oreblock:1>, <techreborn:dust:14> * 3);
	enrichment.addRecipe(<projectred-exploration:ore:3>, <techreborn:dust:14> * 3);
	enrichment.addRecipe(<railcraft:ore_metal>, <techreborn:dust:14> * 3);
	enrichment.addRecipe(<techreborn:ore2>, <techreborn:dust:14> * 3);
	enrichment.addRecipe(<thermalfoundation:ore>, <techreborn:dust:14> * 3);
```
### Now;
That works, and is all fine and dandy, but here is my request. Mekanism currently uses for the crusher:
```
// removeRecipe(IIngredient itemOutput, @Optional IIngredient itemInput);
// addRecipe(IItemStack itemInput, IItemStack itemOutput)
```
And I am requesting that you change it to support the following:
 - The use of IOreDictEntry in the `@Optional IIngredient itemInput` in removeRecipe
 - Let the removeRecipe `IItemStack itemOutput`be set to `<*>`
 - Let the addRecipe `IItemStack itemInput` be an IOreDictEntry

Those Three would let me reduce the above code down to:
```
// Copper
	enrichment.removeRecipe(<*>, <ore:dustCopper> * 2);
	enrichment.addRecipe(<ore:oreCopper>, <techreborn:dust:14> * 3);
```
A massive reduction in script writing for sure. 
### So...
That is my request. Obviously this is for all the machines, and it would be nice if you included all the benefits of the CraftTweaker/ModTweaker API not just the use of the OreDictionary inside of recipes. Either way, or no way, I once again thank you for taking the time to fork and publish Mekanism and wish you the best of luck.

### Total Request:
 - [ ] Expand CraftTweaker/ModTweaker integration
 - [ ] Integrate [MekanismOres](https://minecraft.curseforge.com/projects/mekanismores) into Mekanism
 - [ ] Add config Option to set the order of modID output for all Mekanism machines. (A list is better then a single non-list option.
 - [x]  Make all machines with a gas or fluid input accept any Fluid or Gas
 - [x] Remove (or at least give a config option to disable) Crafttweaker log spam as in aidancbrady#5249

**Comment by pupnewfster** [comment]
It would also actually be nice, to have it so that all the machines that support changing the input gas via CrT actually support all gas types. Some of them are currently hardcoded to only support specific gas types, so even though it allows you to add custom recipes... you can't actually use the recipe, as there is no way to input the gas. (I believe it is hardcoded in the machines canAcceptGas method.)

**Comment by bookerthegeek** [comment]
### Gotcha:
Gas would be nice also. Honestly though I just use either [JAOPCA](https://minecraft.curseforge.com/projects/jaopca?gameCategorySlug=mc-mods&projectID=266936) or [MekanismOres](https://minecraft.curseforge.com/projects/mekanismores) for making sure all the ore types in my pack are integrated. Although......

Would it also be possible to integrate the functionality of MekanismOres into the base CraftTweaker/ModTweaker integration I wonder? That would be pretty sweet if it could be.  I'll add that to the first post.

### Also...
Here I am tweaking my mod-pack and unifying everything because why not right? And I came across a couple of other mods that added in a config that I would love for to have here. The example below is from Nuclearcraft.

```
    # Determines the priority of each mod's ore dictionary entries - earlier mods' IDs in this list have a higher priority. This is used to determine which mod's corresponding item is produced in machine recipes. If no matching mod is found, the default entry is used.
    S:ore_dict_priority <
        techreborn
        railcraft
        nuclearcraft
        immersiveengineering
        minecraft
        thermalfoundation
        mekanism
        appliedenergistics2
     >
```
So, now every machine for example gives the TechReborn output first, then if it does not exist hen from Railcraft and so on. . I could add a recipe to convert all the recipes by hand but an easier way (For me, not you) would be to have an option for the default mod output as a config option.

**Comment by pupnewfster** [comment]
I more meant for custom recipes, given the post was initially about CraftTweaker. I remember at one point trying to setup custom progression, just making some recipes based off of the allowed CraftTweaker params, but then the machine is hard coded to a specific thing. For example the osmium compressor CraftTweaker entry allows specifying a gas, however it only accepts osmium.

**Comment by bookerthegeek** [comment]
> For example the osmium compressor CraftTweaker entry allows specifying a gas, however it only accepts osmium.

Thank makes a lot of sense.

**Comment by kragnoth** [comment]
Also, would be great if you looked into the following issue: https://github.com/aidancbrady/Mekanism/issues/5249

As it creates alot of crafttweaker.log spam

**Comment by bookerthegeek** [comment]
Added to Top Post.

**Comment by dizzyd** [comment]
It'll probably be next week (Mar 10th) before I can get to this, but will see what I can do.

**Comment by pupnewfster** [comment]
@dizzyd I am working on a pull that should cleanup the CraftTweaker Integration. At the very least to reduce/remove the duplicate code and unneeded unchecked casts. Though I probably will also do something for the log spam. I may also look slightly into the oredict support. Depends on how much of a pain that is.

**Comment by dizzyd** [comment]
@pupnewfster - fantastic! Look forward to it.

**Comment by dizzyd** [comment]
@pupnewfster @bookerthegeek please note that this issue has been moved to the new repo: https://github.com/mekanica/mekanica/issues/3
