### ISSUE TITLE
Gas coloration in JEI

### ISSUE THREAD

**Issue by pupnewfster** [dizzyd/Mekanism#17]
Gas coloration in JEI, I saw on Curseforge that you are going to be starting to take a look at making some of your own changes rather than just bug fixing so I recommend you take a look at https://github.com/aidancbrady/Mekanism/pull/5213 . Even if you decide not to recolor the gasses (the second part of that pull), I recommend looking at the first commit and merging that in as that fixes rendering for gasses that color via tint instead of texture.. I made a [coremod](https://minecraft.curseforge.com/projects/mekanism-jei-fix) a little while ago that fixes this (by replacing the GasStackRenderer) and while that should be compatible with your branch of Mekanism, it is probably easier to just merge in the one line commit change, rather than also having to use a coremod.

**Comment by ate0ate** [comment]
I wholeheartedly second this suggestion. I'd love to see the recolors mentioned above and seen in aidancbrady#5028 implemented as well. Realism aside, its just easier to tell them apart from each other that way which is always helpful from a gameplay perspective.

**Comment by dizzyd** [comment]
Generally open to this, but I'm wondering if these liquid textures are able to be placed in the world or anything? Deleting all these assets makes me wonder how it might break existing worlds.

Otherwise, these patches look ok, but I need to work through all the ramifications -- any clarity you can provide would help accelerate that. :)

**Comment by pupnewfster** [comment]
The textures won't break any worlds. As textures are decided at run time for gasses, and Mekanism's gas system isn't using the json format blocks use so does not have a hardcoded texture location. What would break existing worlds would be to change the registry names of the gasses (the linked pull keeps the registry names the same, just changes how they get their texture).

And in terms of the liquid variants, they get their texture in a similar way to gasses so it won't break anything. The most it will do is confuse a couple people why some of their gasses changed color.

Edit: Oh and of course someone should go through and decide if the colors are good or not, as I tried to find real life versions to compare the colors to but for gasses it is sometimes hard. The bright side of it being hex codes is it is easy to tweak quickly.

**Comment by bookerthegeek** [comment]
Personally the colors being realistic is not so much of an issue. Would rather have easily identifiable colors for each material with the different types of a material being a shade off so their is continuity to it.

And if your looking for colors an easy standard for most materuals would be Tinkers Construct as the most easily identifiable mod that adds fluids for materials. Nuclear craft would also be one to grab colors from.

**Comment by pupnewfster** [comment]
Then how they are in the pull probably is fine 
![image](https://user-images.githubusercontent.com/1203288/53895789-c58c6180-4000-11e9-981b-3ff24d48bb42.png)
(They show up twice because liquid, and gas variants)

**Comment by dizzyd** [comment]
I have merged these changes into master and am cutting 9.5.0beta1 with them.
