### ISSUE TITLE
Investigate why there is so much duplicate code in various machines

### ISSUE THREAD

**Issue by dizzyd** [dizzyd/Mekanism#18]
TileEntityElectricMachine
TileEntityDoubleElectricMachine
TileEntityAdvancedElectricMachine
TileEntityMetallurgicInfuser

**Comment by dizzyd** [comment]
Hat tip to @pupnewfster - this was resolved in #27.

**Comment by pupnewfster** [comment]
Minus the fact there is still a lot of duplicated code that needs fixing.
