### ISSUE TITLE
Digital Miner + Nibiru (MorePlanets) Crash

### ISSUE THREAD

**Issue by knoxhack** [dizzyd/Mekanism#2]
Nice maybe you guys can help me with this.

#### Issue description:
Crash when trying to mine ores in Nibiru More Planets dimension.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
Forge 14.23.5.2808

*Mekanism:** 
1.12.2-9.4.13.349

**Other relevant version:** 
Modpack: AstroBlock 1.1.21

#### If a (crash)log is relevant for this issue, link it here: 
https://gist.github.com/knoxhack/69c5ef2ccf34b55aba41edad9c43f365

**Comment by knoxhack** [comment]
https://github.com/NFINIT-Development/AstroBlock/issues/37

**Comment by knoxhack** [comment]
https://github.com/SteveKunG/MorePlanets/issues/56

**Comment by dizzyd** [comment]
This is resolved in HEAD; I'll cut a new release this evening (9.4.16).

**Comment by knoxhack** [comment]
Thanks so much
