### ISSUE TITLE
CraftTweaker problems

### ISSUE THREAD

**Issue by TheSnowyChickens** [dizzyd/Mekanism#20]
#### Issue description:
CraftTweaker integration fail.

![grafik](https://user-images.githubusercontent.com/29357962/53993137-d0ddab00-412e-11e9-838f-d9bb7b8b6004.png)

![grafik](https://user-images.githubusercontent.com/29357962/53993518-eb645400-412f-11e9-8667-28f2755e0847.png)

![grafik](https://user-images.githubusercontent.com/29357962/53993538-fb7c3380-412f-11e9-91cf-92f2861e274f.png)

![grafik](https://user-images.githubusercontent.com/29357962/53993553-08008c00-4130-11e9-8f57-485b543828e2.png)

[scripts.zip](https://github.com/dizzyd/Mekanism/files/2943611/scripts.zip)

#### Steps to reproduce:
1. Install
2. Start
3. Look :=)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2815
**Mekanism:** 1.12.2-9.5.0b1
**Other relevant version:** CT: 4.1.15

#### Other Info:
I had no problems with older versions.

**Comment by pupnewfster** [comment]
If you update MTLib https://minecraft.curseforge.com/projects/mtlib/files/2684561 that should fix the "No recipe found" warnings. Afterwards could you upload/put into pastebin your crafttweaker.log file. Also do you happen to have UniDict, and if so did you change `inputreplacement.mekanism` to true from the default value of false?

Edit: I think I see the issue I messed up a couple spots the order of the params. I will make a pull fixing it shortly.

**Comment by TheSnowyChickens** [comment]
I can't find a special CraftTweaker log, I only have the normal log.
[2019-03-07-2.log.gz](https://github.com/dizzyd/Mekanism/files/2944566/2019-03-07-2.log.gz)

**Comment by pupnewfster** [comment]
For future reference the CraftTweaker log is in the main folder not in the logs folder. But the issue should be fixed in the latest version https://minecraft.curseforge.com/projects/mekanism-dz-edition/files/2684648 (I accidentally was having it try to remove the recipes before they were added in the first place.)

**Comment by TheSnowyChickens** [comment]
Jip, fixed. Ty
![grafik](https://user-images.githubusercontent.com/29357962/54026221-6b74d300-419d-11e9-9162-7e539694ebbc.png)

And here is the log: (it's easy to see, but I was blind at this moment :D )
[crafttweaker.log](https://github.com/dizzyd/Mekanism/files/2945589/crafttweaker.log)

Edit: sry, I don't use UniDict.
