### ISSUE TITLE
info

### ISSUE THREAD

**Issue by robjw95** [dizzyd/Mekanism#3]
I do not know if you are aware of this but the 1.12 branch of mekansim has fixes through nov 19 vs the master branch that you forked with fixes through june 15

**Comment by ate0ate** [comment]
Nice catch there. Should be an easy enough fix for Dizzy. Assuming there are no conflicts he can simply merge the branches.

**Comment by dizzyd** [comment]
Thanks for pointing this out. I've rebased/merged these changes in and released 9.4.15 (pending CF approval, of course).
