### ISSUE TITLE
Version check still points to main Mek repo

### ISSUE THREAD

**Issue by davisjw** [dizzyd/Mekanism#30]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Since you forked away from the official Mekanism repo; you may wish to migrate away from the main mechanism version check url.
URL points to: http://aidancbrady.com/data/versions/Mekanism.txt

Code Location: https://github.com/dizzyd/Mekanism/blob/master/src/main/java/mekanism/common/ThreadGetData.java#L24

**Comment by dizzyd** [comment]
Thanks! I'll look at pulling this out today.
