### ISSUE TITLE
[9.5.0b3] Muffler upgrades working intermittently

### ISSUE THREAD

**Issue by GamertechAU** [dizzyd/Mekanism#31]
#### Issue description:
Muffler upgrades no longer work reliably in certain Mek machines after swapping from Main to the DZ fork.

I've removed all upgrades and reapplied them, as well as breaking and replacing the machines.

Affected machines so far:
Electrolytic Separator (Splitting water only. Another one splitting heavy water stays silent as intended with the same upgrade combos. Removed and re-added muffling to both.)
Elite Crushing Factory
Elite Enriching Factory
Rotary Condensentrator

Elite Smelting and Purification factories stay silent with 4 upgrades so far.

#### Steps to reproduce:
1. Using an Electrolytic Separator as an example, placing the machine, setting to dump and inputting water generates the whistling sound as intended.
2. Adding 2 muffler upgrades and opening the machines UI changes the sound to half volume as intended.
3. Adding the full 4 upgrades and opening the UI makes it silent for a while, before the sound resumes at full volume.
4. Currently using the water one for oxygen, with hydrogen set to dump excess. If I swap oxygen to dump excess (with 4 muffling upgrades), the audio plays. If I change to dump after a bit then the machine goes silent, and stays silent while changing to idle and the oxygen tank refilling. Once it's full, the audio goes full volume again when the machine is used or dumping excess.

Section of debug showing audio related errors: https://pastebin.com/fsphmksR

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2808
**MekanismDZ:** 9.5.0b3
**Mek GeneratorsDZ:** 9.5.0b3

(PS: Thanks for forking and updating Mekanism.)

**Comment by dizzyd** [comment]
Hi @Gamertech - thanks for the bug report. Here's what I've been able to reproduce:

1. Start machine
2. Muffle machine; machine goes silent
3. Machine stops (when full/out of stuff/etc)
4. When Machine resumes, sound resume full volume for a few seconds before re-muffling.

Is the behaviour you're seeing?

Thanks!

**Comment by dizzyd** [comment]
@Gamertech - if what you're seeing matches my above description, I believe I've fixed it. Please feel free to re-open if you're seeing something different. 

Thanks for the report! This fix will be part of beta 4 later today.

**Comment by GamertechAU** [comment]
The behaviour you're mentioning could explain why the electro went silent when I changed from dump to idle, as it just went long enough to end the audio.

I'll try out b4 when I get a chance mate. Cheers for the quick work.

**Comment by GamertechAU** [comment]
Can confirm this is fixed in 1.0.0b1 thanks @dizzyd 

1 minor issue it might pay to show somewhere, the Twitch app doesn't delete the old DZ files when updating to Mekanica. So the pack will fail to load with duplicate files until the user manually deletes the MekanismDZ files.
