### ISSUE TITLE
Mekanism updated

### ISSUE THREAD

**Issue by jburrows82** [dizzyd/Mekanism#35]
I know you guys have been busy doing some refactoring, but it looks like Thiakil got around to cherry picking some issues which you may or may not have pulled in/fixed yourselves before rebasing.

Thank you for forking and updating the mod, btw. Aidan goes on these year long hiatuses every MC version and leaves Mekanism in the hands of contributors that don't give it the love it properly deserves.

**Comment by Apollon-Theos** [comment]
Mekanism (not DZ):Problem with showing icon and tools not corrected. With Forge 2814 I test today.

**Comment by dizzyd** [comment]
There are a variety of bugs that the current maintainer is not including - he's been less than cooperative. Realistically, we'll probably be renaming this fork and moving on. It sucks for everyone, but when a maintainer doesn't want to play ball, I'm not sure how else to proceed. :(

**Comment by ate0ate** [comment]
Aidan has vanished for long periods of time on numerous occasions throughout the years. I'm sure stepping away from things is necessary at times but it does seem that there is a distinct lack of leadership, at least effective leadership, when he does so. That said, I think forking this mod is the best thing to happen to it in a long long time. There is a lot of potential here. Considering Aidan must have been practically a kid when he started Mek it is quite impressive what he managed to pull off. Things like the digital miner and the factory upgrade options or gasses were all ahead of their time for MC mods. There's also ideas that never went anywhere like the voice server or Robit lol. I'm sure the codebase is also a reflection of this change/growth and the years of franken-coding things into working order chasing MC updates and various forge overhauls. Some fresh eyes looking into things and making changes seems like a great thing to me.
