### ISSUE TITLE
Crash while loading modpack

### ISSUE THREAD

**Issue by Yoosk** [dizzyd/Mekanism#4]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Minecraft crashes while loading.

#### Steps to reproduce:
1. Install ATM3 Remix 1.1.0
2. Delete existing mekanism mod files
3. Install mekanismDZ version

#### Version:
**Forge:** forge-14.23.5.2814
**Mekanism:** MekanismDz-1.12.2-9.4.15
**Other relevant version:** ATM3 Remix 1.1.0

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://p.teknik.io/MwcMm
https://p.teknik.io/tjVLm

**Comment by dizzyd** [comment]
Fixed in 9475b27; will be part of 9.4.16 release this evening.
