### ISSUE TITLE
Crash with tinkers table and mekanism tank (rendering tank on table)

### ISSUE THREAD

**Issue by kragnoth** [dizzyd/Mekanism#46]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Crash with tinker crafting table.
When the player places a mekanism tank containing creosote in the tinker's crafting table, the game crashes with the following.

https://hastebin.com/mumufutaho.rb

#### Steps to reproduce:
(this happens on 1.12.2 as of current mekanism fork)
1. Have tinkers construct installed
2. Have mekanism installed
3. Have immersive engineering installed
4. Try to craft treated planks using mekanism tank full of creosote.

Crash with log

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2814
**Mekanism:** MekanismDz-1.12.2-9.5.0b3.jar
**Other relevant version:** 
Immersive engineering: ImmersiveEngineering-0.12-89.jar
Tinker's construct: TConstruct-1.12.2-2.12.0.115.jar

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://hastebin.com/mumufutaho.rb

**Comment by pupnewfster** [comment]
Fixed by #38 currently doing a bit of testing but the fix will be included in the next release.

For now you can either set `allowEmissiveItems` to false in the forge.cfg, or you can disable in the tinkers config rendering of items in world from the tables.

**Comment by dizzyd** [comment]
Hi @kragnoth - this is resolved in the latest release on Curseforge, [1.0.0b1.](https://minecraft.curseforge.com/projects/mekanica/files/2686328). If you have any further issues, please file a new ticket here: https://github.com/mekanica/mekanica/issues
