### ISSUE TITLE
Query for extend

### ISSUE THREAD

**Issue by Apollon-Theos** [dizzyd/Mekanism#6]
Thank you for revive Mekanism!

*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Mekanism and MekanismDz don't have any devices for farming. Plan you extend mod to these theme?
"Actually Additions" and "Integration Foregoing" nave some devices for farm, but  I have some usability claims.

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2805
**Mekanism:** 9.4.16
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by dizzyd** [comment]
Hi @Apollon-Theos - thanks for your suggestion. For the moment, I'm not planning on adding new content to Mekanism; mostly focusing on bug fixes. That may change in the future, of course, but for the moment I'd recommend one of those other mods. :)
