### ISSUE TITLE
Receipt not correct

### ISSUE THREAD

**Issue by Apollon-Theos** [dizzyd/Mekanism#7]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
One piece of Tin Powder fill Metallurgic Infuser to 50 points. That enough to make 5 bronze ingots, but in receipt list show only one ingot.

#### Steps to reproduce:
1. by design
2.
3.
![mekanism-001](https://user-images.githubusercontent.com/46534073/53620010-79a57b00-3c02-11e9-9cee-849075842c10.jpg)
![mekanism-002](https://user-images.githubusercontent.com/46534073/53620017-8033f280-3c02-11e9-859b-7237198bf8e8.jpg)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2805
**Mekanism:** 9.4.16
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by Apollon-Theos** [comment]
In other mods, ratio Tin:Copper is 1:3, and make 4 bronze.
In Mekanism ratio is 1:5, and make 5 bronze.
https://en.wikipedia.org/wiki/Bronze (Ratio is 1:8 (Tin:Copper)) - but this is IRL, not Minecraft :)

**Comment by dizzyd** [comment]
Hi @Apollon-Theos - thanks for pointing this out! I've adjusted the recipes to follow the standard ratio of 1:3 tin:copper = 4 bronze in commit 6cae14f. 

I'll cut a new release later today after I look at another bug.
