### ISSUE TITLE
Socker color for Basic Energy Cube

### ISSUE THREAD

**Issue by Apollon-Theos** [dizzyd/Mekanism#9]
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
For output socket color nor changed to "dark-red"
![mekanism-003](https://user-images.githubusercontent.com/46534073/53664149-cdeb4200-3c78-11e9-8b4b-9a964b5ad71a.jpg)
![mekanism-004](https://user-images.githubusercontent.com/46534073/53664167-d479b980-3c78-11e9-9b58-4b777666c996.jpg)

#### Steps to reproduce:
1. by design
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2805
**Mekanism:** 9.4.17
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by Apollon-Theos** [comment]
Maybe mark buttons in a dialog for config sockets by letters N-north, S-south, U-upper and so on?

**Comment by dizzyd** [comment]
As with every other socket in the mod, the colors don't change based on in/out. The energy cube does have a _slightly_ different overlay when you change input/output but unless you're looking for it, it can be nigh impossible to see. As with #10, this would be a fairly large change to make at this time and I'm not ready to make these kind of sweeping changes...yet. :)
